### PR TITLE
Generic Describe

### PR DESCRIPTION
**Pull request by jmthibault79**
Part of DSDEV-1994

### CODE REVIEW

**Comment by rushtong** [comment]
Having trouble with the tests using `src/test/resources/testing.conf` 
That file should probably be updated to match `application.conf`

**Comment by rushtong** [comment]
It doesn't look like we have a mock server to handle the entities requests. I get these errors when testing.conf is (updated and) used:

```
[info] GenericServiceSpec:
[info] GenericService
[info]   when accessing the /entities/v1 path
[info]   - POST should store a new uBAM generically *** FAILED ***
[info]     404 Not Found was not equal to 200 OK (GenericServiceSpec.scala:50)
[info]   - fetchEntity should retrieve the uBAM *** FAILED ***
[info]     404 Not Found was not equal to 200 OK (GenericServiceSpec.scala:84)
[info]   - fetchEntity on an unknown id should return a not found error
[info]   - findDownstream from the uBAM ought to return the bam and bai files *** FAILED ***
[info]     404 Not Found was not equal to 200 OK (GenericServiceSpec.scala:102)
[info]   - findUpstream from the bam ought to return the uBAM *** FAILED ***
[info]     404 Not Found was not equal to 200 OK (GenericServiceSpec.scala:133)
```

**Comment by jmthibault79** [comment]
True - I didn't do anything Mock-related for this PR

**Comment by rushtong** [comment]
:+1:  Love the extended code documentation.

The failing tests are specific to the mock services so if that is deemed out of scope, then this looks good.

**Pull request merged**
